server:
  port: 8032
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  sleuth:
    sampler:
      probability: 1.0
  data:
    mongodb:
      authentication-database: admin
      username: backtest
      password: backtest
      database: catalogos
      port: 27017
      host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
    sender:
      type: rabbit
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
