server:
  port: 8034
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movies
    username: backtest
    password: backtest
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    baseUrl: http://localhost:9411/
    ensbled: true
    sender:
      type: rabbit
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  sleuth:
    sampler:
      probability: 1.0
    
